name: build

on:
  workflow_call:
  # push:
  #   branches: [ master ]
  #   paths-ignore:
  #     - '/*.sh'
  #     - '/.*'
  #     - '/_*'
  #     - '/vcpkg.txt'
  #     - 'docs/**'
  #     - '**.adoc'
  #     - '**.md'
  #     - '**.nix'
  #     - 'flake.lock'
  #     - '.github/workflows/*.yml'
  #     - '!.github/workflows/build.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

env:
  CACHE_DIR: installs

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        foo: ['bar', 'baz']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache
        id: build_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.foo }}-${{ hashFiles('.github/workflows/**') }}

      - name: Build cache
        if: steps.build_cache.outputs.cache-hit != 'true'
        run: |
          for i in dist; do mkdir -p ${{ env.CACHE_DIR }}/"$i"; done
          echo "built ${{ matrix.foo }}: $(date)" > dist/status.txt
          for i in dist; do cp -a "$i" ${{ env.CACHE_DIR }}/"$i"; done
          echo ls -la ${{ env.CACHE_DIR }}
          ls -la ${{ env.CACHE_DIR }}

      - run: 'echo "${{ matrix.foo }}: This is a build"'
