name: build

on:
  workflow_call:
  # push:
  #   branches: [ master ]
  #   paths-ignore:
  #     - '/*.sh'
  #     - '/.*'
  #     - '/_*'
  #     - '/vcpkg.txt'
  #     - 'docs/**'
  #     - '**.adoc'
  #     - '**.md'
  #     - '**.nix'
  #     - 'flake.lock'
  #     - '.github/workflows/*.yml'
  #     - '!.github/workflows/build.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

env:
  CACHE_DIR: installs

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        foo: ['bar', 'baz']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache
        id: build_cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.foo }}-${{ hashFiles('.github/workflows/**') }}

      # For rsync support in Windows
      - uses: GuillaumeFalourd/setup-rsync@v1

      - name: Build cache
        if: steps.build_cache.outputs.cache-hit != 'true'
        shell: bash
        run: |

          # Simulate building:
          mkdir -p dist
          echo "built ${{ matrix.foo }}-${{ runner.os }}: $(date)" > dist/status.txt
          echo cat dist/status.txt
          cat dist/status.txt

          # Move built stuff into cache
          # But first, due to GitHub's stupid cp, need to pre-create dest dirs.
          # But first, due to GitHub's stupid cp, need to use rsync instead.
          for i in dist; do \
            rsync -a "$i" ${{ env.CACHE_DIR }}; \
          done
          echo ls -la ${{ env.CACHE_DIR }}
          ls -la ${{ env.CACHE_DIR }}
          echo ls -la ${{ env.CACHE_DIR }}/*
          ls -la ${{ env.CACHE_DIR }}/*

      - run: 'echo "${{ matrix.foo }}: This is a build"'
